name: Get Citation Data

on: 
 page_build: 
 schedule:
  - cron:  '0 8 * * 0'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install Reqs
      run: |
        sudo apt-get install python3-setuptools
    - name: Run
      run: |
        cd ./scripts
        pip3 install scholarly
        python3 scholar_crawler.py
        git init
        git config --local user.name "${GITHUB_ACTOR}"
        export remote_repo="https://${GITHUB_ACTOR}:${{ secrets.GITHUB_TOKEN }}@github.com/${GITHUB_REPOSITORY}.git"
        git add scholar.json
        git commit -m "Updated Citation Data"
        git push "${remote_repo}" HEAD:master