name: Get Citation Data

on: 
 page_build: 
 schedule:
  - cron:  '0 8 * * 0'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install Reqs
      run: |
        sudo apt-get install python3-setuptools
    - name: Run
      run: |
        pip3 install scholarly
        python3 ./scripts/scholar_crawler.py
        git config --local user.name "${{ github.actor }}"
        git config --local user.email "${{ github.actor }}@users.noreply.github.com"
        git add scholar.json
        git commit -m "Updated citation data"
        git push "https://${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository}}.git" HEAD:master