name: Automatic Information Update

on: 
 page_build: 
 schedule:
  - cron:  '0 8 * * 0'

jobs:
  build:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0  # Fetch all history for the repository
        token: ${{ secrets.GITHUB_TOKEN }} # Use the GitHub token to push changes

    - name: Install Reqs
      run: |
        sudo apt-get install python3-setuptools
        pip3 install scholarly
        pip3 install gitpython

    - name: Execute scripts
      run: |
        cd ./scripts
        python3 scholar_crawler.py
        python3 sitemap_generator.py

    - name: Commit and Push Changes
      run: |
        git config --local user.name "${{ github.actor }}"
        git config --local user.email "${{ github.actor }}@users.noreply.github.com"
        git add scripts/scholar.json
        git add sitemap.xml
        git commit -m "Automatic information update"
        git push
